name: ci-test
on:
  push

jobs:
  linting:
    name: Phase Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: lint
        run: |
          echo "*****   ENVIRONMENT   *****"
          env
          echo "*****   ENVIRONMENT   *****"
          make lint
          

  testing:
    name: Phase Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: test-level-01
        run: |
          echo "*****   ENVIRONMENT   *****"
          env
          echo "*****   ENVIRONMENT   *****"
          make test-level-01
      - name: test-level-02
        run: |
          make test-level-02
