name: ci-test
on:
  - push
  - pull_request



jobs:
  linting:
    name: Phase Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip3 install -r requirements-dev.txt

      - name: lint
        run: |
          make lint
          

  testing:
    name: Phase Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Python tools
        run: |
          pip3 install -r requirements-dev.txt

      - name: test-level-01
        run: |
          make test-level-01
      
      - name: test-level-02
        run: |
          make test-level-02

      - name: SonarCloud Scan
        if: ${{ github.event_name == 'pull_request' }}
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
